class MainPageLocators:
    COOKIE_POPUP = "div[id='cookie-popup-with-overlay']"
    ACCEPT_ALL_COOKIES = "button.cookie-popup-with-overlay__button[data-ref='cookie.accept-all']"
    RETURN_TRIP = "fsw-trip-type-button[data-ref='flight-search-trip-type__return-trip']"
    SINGLE_TRIP = "fsw-trip-type-button[data-ref='flight-search-trip-type__one-way-trip']"
    TEXTBOX_DEPARTURE_ID = "input-button__departure"
    TEXTBOX_DESTINATION_ID = "input-button__destination"
    BUTTON_CLEAR_DESTINATION = "button.list__clear-selection.ry-button--anchor-blue.ry-button--anchor"
    FLIGHT_COUNTRIES_TITLE = "div.h4.countries__title"
    FLIGHT_COUNTRIES = "span.countries__country-inner"
    FLIGHT_AIRPORTS_TITLE = "div.list__header-title"
    FLIGHT_AIRPORTS = "span[data-ref='airport-item__name']"
    TEXTBOX_DEPARTURE_CALENDAR = "div.input-button__content[data-ref='input-button__dates-from']"
    TEXTBOX_DESTINATION_CALENDAR = "div.input-button__content[data-ref='input-button__dates-to']"
    DEPARTURE_CALENDAR_DATE = "div.calendar-body__cell[data-ir='%s']"
